name: Build, lint, test

on:
  push:
  pull_request:
    branches: [master]

jobs:

  test:
    strategy:
      matrix:
        os: ['ubuntu-latest', 'windows-latest', 'macos-latest']
        node-version: [14.x, 16.x, 18.x]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: bash ci/test.sh
        shell: bash
     
